server {
    listen 80;
    
    # Change this line to match your new free domain name string
    server_name reactapppppp.duckdns.org;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}