name: React App Dockerized Automated EC2 CI/CD Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code Repository
        uses: actions/checkout@v4

      - name: Deploy and Launch Docker Container inside AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/react-app
            
            # Pull the latest source code additions
            git reset --hard
            git pull origin main
            
            # Build the new Docker Image using the container blueprint
            docker build -t react-web-app:latest .
            
            # Safely shut down and remove the old running container version if it exists
            docker stop react-container || true
            docker rm react-container || true
            
            # Run the fresh container, mapping port 80 of the server to port 80 of the container
            docker run -d --name react-container -p 80:80 react-web-app:latest
